import {
  Program,
  FAQ,
  ContentItem,
  InterestSubmission,
  ContactMessage,
  SiteSetting,
  Profile,
} from '../../types';

export const DEMO_PROGRAMS: Program[] = [
  {
    id: 'p-1',
    title: 'Akademi Kepemimpinan Muda 2026',
    slug: 'akademi-kepemimpinan-muda-2026',
    short_description: 'Pelatihan kepemimpinan intensif untuk melatih calon pemimpin muda berintegritas dan berdampak sosial.',
    description: `Akademi Kepemimpinan Muda 2026 adalah program inkubasi kepemimpinan selama 8 minggu yang dirancang khusus untuk pemuda Indonesia usia 18-25 tahun. 

Program ini menggabungkan sesi materi interaktif, analisis studi kasus, pendampingan mentor profesional, dan aksi dampak sosial langsung di masyarakat. Peserta akan mempelajari manajemen tim, komunikasi publik, kepemimpinan beretika, serta desain proyek inovasi sosial.`,
    category: 'Kepemudaan',
    target_audience: 'Pemuda, Mahasiswa, dan Fresh Graduate usia 18-25 tahun seluruh Indonesia',
    objectives: [
      'Meningkatkan keterampilan kepemimpinan strategis dan beretika',
      'Melatih kemampuan komunikasi serta negosiasi di ranah publik',
      'Mendorong realisasi proyek sosial yang berdampak nyata bagi komunitas',
    ],
    benefits: [
      'Sertifikat Kelulusan Resmi dari Platform MudaConnect',
      'Akses Jejaring Mentor Nasional dan Industri Sosial',
      'Kesempatan Pendanaan Hibah Proyek Dampak Sosial Pilihan',
      'Modul & Rekaman Sesi Pembelajaran Seumur Hidup',
    ],
    requirements: [
      'Warga Negara Indonesia usia 18-25 tahun',
      'Memiliki komitmen mengikuti seluruh rangkaian acara (8 minggu)',
      'Memiliki gagasan atau minat dalam isu pengembangan sosial/masyarakat',
      'Dapat berpartisipasi secara aktif dalam diskusi kelompok',
    ],
    delivery_mode: 'hybrid',
    location: 'Jakarta & Online via Zoom',
    start_date: '2026-08-15',
    end_date: '2026-10-10',
    registration_status: 'interest_open',
    fee_information: 'Gratis (Beasiswa Penuh untuk 50 Peserta Terpilih)',
    contact_information: 'program@mudaconnect.ai | WhatsApp: 0812-3456-7890',
    cover_image_path: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80',
    is_featured: true,
    status: 'published',
    created_at: '2026-06-01T10:00:00Z',
    updated_at: '2026-07-01T10:00:00Z',
  },
  {
    id: 'p-2',
    title: 'Bootcamp Keterampilan Digital & AI Pemuda',
    slug: 'bootcamp-keterampilan-digital-ai-pemuda',
    short_description: 'Kuasai penggunaan AI, analitik data, dan alat digital modern untuk mempercepat karir pemuda di era teknologi.',
    description: `Di era kecerdasan buatan, keterampilan memanfaatkan AI secara bijak dan efektif menjadi kunci keberhasilan karir. Bootcamp ini memberikan pelatihan praktis penggunaan alat-alat AI modern, analisis data tingkat dasar, serta prompt engineering untuk efisiensi kerja dan inovasi bisnis.`,
    category: 'Keterampilan Digital',
    target_audience: 'Pemuda, Pelajar, Mahasiswa, dan Pencari Kerja Muda usia 17-28 tahun',
    objectives: [
      'Memahami dasar-dasar AI, Etika Teknologi, dan Prompt Engineering',
      'Meningkatkan produktivitas kerja dengan otomasi dan alat bantu AI',
      'Membangun portofolio digital berbasis solusi nyata',
    ],
    benefits: [
      'Portofolio Praktis Berbasis Proyek Nyata',
      'Sertifikat Kompetensi Digital Pemuda',
      'Grup Diskusi & Komunitas Pembelajar AI Indonesia',
    ],
    requirements: [
      'Memiliki akses laptop/komputer dan koneksi internet stabil',
      'Memiliki rasa ingin tahu tinggi terhadap teknologi AI',
    ],
    delivery_mode: 'online',
    location: 'Online via Zoom & Discord',
    start_date: '2026-09-01',
    end_date: '2026-09-30',
    registration_status: 'interest_open',
    fee_information: 'Bebas Biaya Program',
    contact_information: 'digital@mudaconnect.ai',
    cover_image_path: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80',
    is_featured: true,
    status: 'published',
    created_at: '2026-06-10T10:00:00Z',
    updated_at: '2026-07-05T10:00:00Z',
  },
  {
    id: 'p-3',
    title: 'Inkubasi Kewirausahaan Sosial Muda',
    slug: 'inkubasi-kewirausahaan-sosial-muda',
    short_description: 'Ubah ide bisnis sosialmu menjadi wirausaha berkelanjutan dengan bimbingan praktisi dan pendampingan bisnis.',
    description: `Program Inkubasi Kewirausahaan Sosial Muda membantu wirausahawan pemuda merancang model bisnis sosial (socio-entrepreneurship) yang terukur, berdampak, dan menguntungkan. Meliputi materi validation market, financial modeling, hingga pitching di hadapan investor dampak sosial.`,
    category: 'Kewirausahaan',
    target_audience: 'Pendiri rintisan bisnis sosial muda usia 18-30 tahun',
    objectives: [
      'Merancang Business Model Canvas Berbasis Dampak Sosial',
      'Menyusun strategi validasi pasar dan manajemen keuangan rintisan',
      'Mempersiapkan presentasi investasi (Pitch Deck) yang meyakinkan',
    ],
    benefits: [
      'Mentoring 1-on-1 dengan Business Coach',
      'Akses ke Investor Dampak Sosial & Jaringan Funder',
      'Kesempatan Eksibisi Proyek Kewirausahaan',
    ],
    requirements: [
      'Tim terdiri dari 2-4 orang pemuda',
      'Sudah memiliki prototipe atau produk/jasa minimal (MVP)',
    ],
    delivery_mode: 'hybrid',
    location: 'Bandung & Online',
    start_date: '2026-10-01',
    end_date: '2026-12-15',
    registration_status: 'coming_soon',
    fee_information: 'Gratis melalui Seleksi Proposal Proposal',
    contact_information: 'entrepreneur@mudaconnect.ai',
    cover_image_path: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=80',
    is_featured: true,
    status: 'published',
    created_at: '2026-06-15T10:00:00Z',
    updated_at: '2026-07-08T10:00:00Z',
  },
  {
    id: 'p-4',
    title: 'Lokakarya Edukasi Lingkungan & Aksi Iklim',
    slug: 'lokakarya-edukasi-lingkungan-aksi-iklim',
    short_description: 'Gerakan kepemudaan untuk literasi ekologi, manajemen sampah, dan aksi nyata pelestarian lingkungan lokal.',
    description: `Aksi iklim dimulai dari pemuda setempat. Lokakarya ini mengajak generasi muda memahami tantangan krisis iklim global serta melakukan langkah nyata seperti kampanye bebas sampah, penghijauan perkotaan, dan audit jejak karbon komunitas.`,
    category: 'Sosial',
    target_audience: 'Komunitas pemuda dan sukarelawan lingkungan usia 15-25 tahun',
    objectives: [
      'Meningkatkan kesadaran isu ekologi dan perubahan iklim',
      'Menerapkan praktik pengelolaan sampah terpadu di lingkungan rumah',
    ],
    benefits: [
      'Sertifikat Volunter Lingkungan',
      'Kit Aksi Ramah Lingkungan',
    ],
    requirements: [
      'Terbuka untuk umum',
      'Bersedia hadir pada aksi komunitarian lokal',
    ],
    delivery_mode: 'offline',
    location: 'Taman Kota Jakarta & Surabaya',
    start_date: '2026-07-25',
    end_date: '2026-07-26',
    registration_status: 'ongoing',
    fee_information: 'Gratis',
    contact_information: 'sosial@mudaconnect.ai',
    cover_image_path: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=80',
    is_featured: false,
    status: 'published',
    created_at: '2026-05-01T10:00:00Z',
    updated_at: '2026-07-01T10:00:00Z',
  },
  {
    id: 'p-5',
    title: 'Kelas Literasi Finansial & Mental Health Pemuda',
    slug: 'kelas-literasi-finansial-mental-health-pemuda',
    short_description: 'Seri webinar interaktif untuk pengelolaan keuangan pribadi dan ketahanan mental generasi muda.',
    description: `Navigasi kehidupan dewasa muda sering menghadapi tantangan finansial dan tekanan mental. Seri webinar ini menghadirkan perencana keuangan tersertifikasi dan psikolog klinis untuk memberikan panduan praktis pengelolaan budget, investasi aman, serta strategi coping mechanism yang sehat.`,
    category: 'Pengembangan Diri',
    target_audience: 'Pelajar, Mahasiswa, dan Pekerja Muda usia 18-27 tahun',
    objectives: [
      'Membuat perencanaan keuangan pribadi yang realistis',
      'Mengenali gejala stress dan menjaga kesehatan mental secara mandiri',
    ],
    benefits: [
      'E-book Templat Budgeting & Self-Care Checklist',
      'Sertifikat Kehadiran Webinar',
    ],
    requirements: ['Pendaftaran terbuka untuk siapa saja'],
    delivery_mode: 'online',
    location: 'Online via Live YouTube & Zoom',
    start_date: '2026-06-01',
    end_date: '2026-06-15',
    registration_status: 'completed',
    fee_information: 'Gratis',
    contact_information: 'edukasi@mudaconnect.ai',
    cover_image_path: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80',
    is_featured: false,
    status: 'published',
    created_at: '2026-04-10T10:00:00Z',
    updated_at: '2026-06-16T10:00:00Z',
  },
];

export const DEMO_FAQS: FAQ[] = [
  {
    id: 'f-1',
    category: 'Umum',
    question: 'Apa itu MudaConnect?',
    answer: 'MudaConnect adalah platform digital yang dirancang untuk membantu pemuda Indonesia menemukan program, kegiatan, pelatihan, dan konten edukasi secara terpusat serta praktis.',
    keywords: ['mudaconnect', 'platform', 'definisi', 'pemuda', 'peluang'],
    sort_order: 1,
    is_popular: true,
    status: 'published',
    created_at: '2026-06-01T10:00:00Z',
  },
  {
    id: 'f-2',
    category: 'Program',
    question: 'Siapa saja yang dapat mengikuti program di MudaConnect?',
    answer: 'Secara umum, program ditujukan untuk pemuda Indonesia usia 15-30 tahun, baik pelajar, mahasiswa, fresh graduate, maupun profesional muda. Setiap program memiliki kriteria target khusus yang tertera pada detail program.',
    keywords: ['peserta', 'syarat', 'usia', 'kriteria'],
    sort_order: 2,
    is_popular: true,
    status: 'published',
    created_at: '2026-06-01T10:00:00Z',
  },
  {
    id: 'f-3',
    category: 'Pendaftaran',
    question: 'Bagaimana cara mengisi dan mengirimkan Formulir Minat?',
    answer: 'Kamu dapat membuka halaman detail program yang diminati atau langsung menuju halaman /minat, memilih program pilihan, mengisi data diri dengan benar, dan menekan tombol Kirim Formulir Minat.',
    keywords: ['form minat', 'pendaftaran', 'cara daftar', 'formulir'],
    sort_order: 3,
    is_popular: true,
    status: 'published',
    created_at: '2026-06-01T10:00:00Z',
  },
  {
    id: 'f-4',
    category: 'Pendaftaran',
    question: 'Apakah pengisian formulir minat sama dengan konfirmasi pendaftaran?',
    answer: 'Bukan. Pengisian formulir minat merupakan indikasi awal minat kamu pada program. Tim MudaConnect atau panitia program akan meninjau data dan mengirimkan konfirmasi pendaftaran resmi melalui email/WhatsApp jika lolos seleksi.',
    keywords: ['konfirmasi', 'perbedaan', 'seleksi', 'minat'],
    sort_order: 4,
    is_popular: true,
    status: 'published',
    created_at: '2026-06-01T10:00:00Z',
  },
  {
    id: 'f-5',
    category: 'Biaya',
    question: 'Apakah program-program di platform ini dipungut biaya?',
    answer: 'Sebagian besar program yang disajikan adalah program gratis atau bersubsidi penuh. Detail biaya (jika ada) selalu dicantumkan secara transparan pada halaman detail masing-masing program.',
    keywords: ['biaya', 'bayar', 'gratis', 'beasiswa'],
    sort_order: 5,
    is_popular: true,
    status: 'published',
    created_at: '2026-06-01T10:00:00Z',
  },
  {
    id: 'f-6',
    category: 'Sertifikat',
    question: 'Apakah peserta akan mendapatkan sertifikat kelulusan?',
    answer: 'Peserta yang menyelesaikan seluruh rangkaian kegiatan dan memenuhi syarat kehadiran/tugas akan mendapatkan e-Sertifikat resmi.',
    keywords: ['sertifikat', 'e-sertifikat', 'kelulusan'],
    sort_order: 6,
    is_popular: false,
    status: 'published',
    created_at: '2026-06-01T10:00:00Z',
  },
  {
    id: 'f-7',
    category: 'Kontak',
    question: 'Bagaimana cara menghubungi pengelola jika memiliki pertanyaan khusus?',
    answer: 'Kamu bisa menggunakan fasilitas MudaBot di pojok kanan bawah atau mengirimkan pesan langsung melalui halaman Kontak.',
    keywords: ['kontak', 'hubungi', 'bantuan', 'pertanyaan'],
    sort_order: 7,
    is_popular: false,
    status: 'published',
    created_at: '2026-06-01T10:00:00Z',
  },
];

export const DEMO_CONTENTS: ContentItem[] = [
  {
    id: 'c-1',
    title: '5 Keterampilan Esensial yang Harus Dimiliki Pemuda di Era AI',
    slug: '5-keterampilan-esensial-pemuda-era-ai',
    content_type: 'article',
    excerpt: 'Memahami bagaimana kecerdasan buatan mengubah lanskap kerja dan keterampilan adaptif yang wajib kamu tingkatkan.',
    body: `Kecerdasan Buatan (AI) berkembang sangat pesat. Bagi generasi muda, kehadiran AI bukanlah ancaman melainkan penguat potensi.

Berikut 5 keterampilan esensial yang sangat dibutuhkan di era AI:
1. Critical Thinking & Problem Solving — AI dapat menghasilkan data, namun manusia yang memverifikasi dan mengambil keputusan strategis.
2. Prompt Engineering & Literasi Digital — Kemampuan berkomunikasi secara efektif dengan model AI untuk menghasilkan output presisi.
3. Emotional Intelligence & Empathy — Kepemimpinan dan kerjasama tim membutuhkan empati emosional yang tak dimiliki mesin.
4. Adaptabilitas Pembelajaran Mandiri — Kesiapan untuk terus belajar hal baru selaras perkembangan teknologi.
5. Etika & Tanggung Jawab Teknologi — Kesadaran akan privasi data, bias AI, dan dampak sosial dari aplikasi teknologi.`,
    media_path: null,
    thumbnail_path: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80',
    alt_text: 'Diskusi pemuda tentang teknologi digital',
    status: 'published',
    created_at: '2026-07-10T10:00:00Z',
    updated_at: '2026-07-10T10:00:00Z',
  },
  {
    id: 'c-2',
    title: 'Podcast MudaBicara #01: Menemukan Passion dan Membangun Dampak Sosial',
    slug: 'podcast-mudabicara-01-passion-dan-dampak-sosial',
    content_type: 'audio',
    excerpt: 'Dengarkan perbincangan hangat bersama pemuda penggerak komunitas lokal mengenai langkah awal memulai aksi sosial.',
    body: 'Dalam episode perdana Podcast MudaBicara, kita berbincang dengan pendiri Gerakan Pemuda Berdampak tentang bagaimana mengubah ide sederhana menjadi aksi sosial nyata yang konsisten.',
    media_path: 'https://cdn.freesound.org/previews/588/588234_11861866-lq.mp3',
    thumbnail_path: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=800&q=80',
    alt_text: 'Microphone podcast studio',
    status: 'published',
    created_at: '2026-07-08T10:00:00Z',
    updated_at: '2026-07-08T10:00:00Z',
  },
  {
    id: 'c-3',
    title: 'Video Panduan: Cara Membuat Proposal Proyek Kepemudaan yang Menarik',
    slug: 'video-panduan-membuat-proposal-proyek-kepemudaan',
    content_type: 'video',
    excerpt: 'Simak tutorial ringkas struktur penulisan proposal kegiatan agar disetujui sponsor dan mitra organisasi.',
    body: 'Proposal yang kuat harus menyampaikan latar belakang masalah yang rinci, tujuan terukur, anggaran realistis, serta indikator keberhasilan yang jelas.',
    media_path: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail_path: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
    alt_text: 'Presentasi materi proposal',
    status: 'published',
    created_at: '2026-07-05T10:00:00Z',
    updated_at: '2026-07-05T10:00:00Z',
  },
  {
    id: 'c-4',
    title: 'Dokumentasi Aksi Bersihkan Pantai bersama Relawan Muda',
    slug: 'dokumentasi-aksi-bersihkan-pantai-relawan-muda',
    content_type: 'image',
    excerpt: 'Galeri foto kegiatan kolaborasi pemuda dalam upaya penanggulangan sampah laut di pesisir.',
    body: 'Lebih dari 120 relawan pemuda berkumpul akhir pekan lalu dan berhasil mengumpulkan 450 kg sampah plastik yang dipilah untuk didaur ulang.',
    media_path: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=1200&q=80',
    thumbnail_path: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=800&q=80',
    alt_text: 'Aksi relawan pemuda memilah sampah pantai',
    status: 'published',
    created_at: '2026-07-01T10:00:00Z',
    updated_at: '2026-07-01T10:00:00Z',
  },
];

export const DEMO_SUBMISSIONS: InterestSubmission[] = [
  {
    id: 'sub-1',
    full_name: 'Budi Santoso',
    email: 'budi.santoso@example.com',
    phone: '081234567891',
    domicile: 'Bandung',
    age_range: '18-24',
    program_id: 'p-1',
    program_title: 'Akademi Kepemimpinan Muda 2026',
    motivation: 'Saya ingin mengembangkan keterampilan kepemimpinan untuk mengelola organisasi mahasiswa di kampus.',
    status: 'new',
    admin_notes: 'Pengajuan baru, perlu ditinjau kesesuaian kualifikasi.',
    created_at: '2026-07-20T08:30:00Z',
  },
  {
    id: 'sub-2',
    full_name: 'Siti Rahmawati',
    email: 'siti.rahma@example.com',
    phone: '081987654321',
    domicile: 'Jakarta Selatan',
    age_range: '18-24',
    program_id: 'p-2',
    program_title: 'Bootcamp Keterampilan Digital & AI Pemuda',
    motivation: 'Ingin menguasai prompt engineering untuk membantu tugas kuliah dan riset digital.',
    status: 'reviewed',
    admin_notes: 'Sudah ditinjau. Memenuhi syarat latar belakang.',
    created_at: '2026-07-19T14:15:00Z',
  },
  {
    id: 'sub-3',
    full_name: 'Andi Wijaya',
    email: 'andi.w@example.com',
    phone: '085612347890',
    domicile: 'Surabaya',
    age_range: '25-30',
    program_id: 'p-3',
    program_title: 'Inkubasi Kewirausahaan Sosial Muda',
    motivation: 'Memiliki prototipe aplikasi pengelolaan sampah dapur dan mencari pendampingan bisnis.',
    status: 'contacted',
    admin_notes: 'Sudah dihubungi via email untuk jadwal wawancara awal.',
    created_at: '2026-07-18T11:00:00Z',
  },
];

export const DEMO_MESSAGES: ContactMessage[] = [
  {
    id: 'msg-1',
    full_name: 'Dewi Lestari',
    email: 'dewi.lestari@example.com',
    subject: 'Pertanyaan Kemitraan Komunitas',
    message: 'Halo tim MudaConnect, kami dari Komunitas Pemuda Kreatif Malang ingin mengajukan kolaborasi program pelatihan digital.',
    status: 'unread',
    created_at: '2026-07-21T09:00:00Z',
  },
  {
    id: 'msg-2',
    full_name: 'Rian Hidayat',
    email: 'rian.hidayat@example.com',
    subject: 'Kendala Pengisian Form Minat',
    message: 'Apakah ada batas waktu pasti untuk pengisian formulir minat Akademi Kepemimpinan Muda 2026?',
    status: 'read',
    admin_notes: 'Telah dijawab melalui surel bahwa pendaftaran hingga awal Agustus.',
    created_at: '2026-07-17T16:20:00Z',
  },
];

export const DEMO_SETTINGS: SiteSetting = {
  id: 'st-1',
  site_name: 'MudaConnect',
  tagline: 'Temukan Program, Kembangkan Potensi, Ciptakan Dampak.',
  hero_title: 'Temukan Program yang Membantu Kamu Tumbuh dan Berdampak',
  hero_description: 'Jelajahi program, kegiatan, pelatihan, dan konten pengembangan diri untuk mendukung potensi generasi muda Indonesia.',
  contact_email: 'info@mudaconnect.ai',
  contact_phone: '0812-3456-7890',
  address: 'Bandung & Jakarta, Indonesia',
  social_instagram: 'https://instagram.com/mudaconnect.ai',
  social_linkedin: 'https://linkedin.com/company/mudaconnect-ai',
  social_youtube: 'https://youtube.com/@mudaconnect-ai',
  disclaimer: '',
  prototype_mode: false,
  chatbot_enabled: true,
  maintenance_mode: false,
};

export const DEMO_PROFILES: Profile[] = [
  {
    id: 'admin-1',
    email: 'admin@mudaconnect.ai',
    full_name: 'Administrator MudaConnect',
    role: 'super_admin',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
];
